DjMemoryGetSys/loginApp/urls.py
from django.urls import path
from .views import login, register, logout

app_name = 'loginApp'

urlpatterns = [
    path('', login, name='login'),
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),
]

DjMemoryGetSys/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('loginApp.urls'), name="loginApp1"),
    path('home/', include('homeApp.urls'), name='homeApp'),
    re_path(r'^.*$', include('homeApp.urls'), name="homeAll")
]

DjMemoryGetSys/headerApp/templates/header.html
<header class="cd-main-header">
    <div class="cd-logo">
        <span style="font-size: 16.5px; color: white;">后台管理系统</span>
    </div>

    <div class="cd-search is-hidden">
        <form action="#">
            <input type="search" placeholder="Search..." />
        </form>
    </div> <!-- cd-search -->

    <a href="javascript:void(0);" class="cd-nav-trigger">Menu<span></span></a>

    <nav class="cd-nav">
        <ul class="cd-top-nav">
            <li class="has-children">
                <a href="javascript:void(0);"  style="display: flex; align-items: center;">
                    <!-- <i class="glyphicon glyphicon-envelope"></i> -->

                     <svg id="notices" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-bell" viewBox="0 0 16 16">
                        <path
                            d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z" />
                    </svg>
                    <span class="badge bg-red">23</span>
                </a>
                <ul>
                    <li><a href="#" target="main_iframe"><i class="glyphicon glyphicon-user"></i> My
                            Account1</a>
                    </li>
                    <li><a href="#" target="main_iframe"><i class="glyphicon glyphicon-edit"></i> Edit
                            Account1</a>
                    </li>
                    <li><a href="#"><i class="glyphicon glyphicon-log-out"></i>Logout1</a></li>
                </ul>
            </li>
            <li class="has-children">
                <a href="javascript:void(0);" style="display: flex; align-items: center;">
                    <svg  id="messages" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-chat-dots" viewBox="0 0 16 16">
                        <path
                            d="M5 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                        <path
                            d="m2.165 15.803.02-.004c1.83-.363 2.948-.842 3.468-1.105A9.06 9.06 0 0 0 8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6a10.437 10.437 0 0 1-.524 2.318l-.003.011a10.722 10.722 0 0 1-.244.637c-.079.186.074.394.273.362a21.673 21.673 0 0 0 .693-.125zm.8-3.108a1 1 0 0 0-.287-.801C1.618 10.83 1 9.468 1 8c0-3.192 3.004-6 7-6s7 2.808 7 6c0 3.193-3.004 6-7 6a8.06 8.06 0 0 1-2.088-.272 1 1 0 0 0-.711.074c-.387.196-1.24.57-2.634.893a10.97 10.97 0 0 0 .398-2z" />
                    </svg>
                    <span class="badge bg-red">13</span>
                </a>
                <ul>
                    <li><a href="#" target="main_iframe"><i class="glyphicon glyphicon-user"></i> My
                            Account1</a>
                    </li>
                    <li><a href="#" target="main_iframe"><i class="glyphicon glyphicon-edit"></i> Edit
                            Account1</a>
                    </li>
                    <li><a href="#"><i class="glyphicon glyphicon-log-out"></i> Logout1</a></li>
                </ul>
            </li>
            <li class="has-children" >
                <a href="javascript:void(0);" id="user" style="display: flex; align-items: center;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                        class="bi bi-person" viewBox="0 0 16 16">
                        <path
                            d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                    </svg>
                    <span id="username">{{ user.username }}</span>
                </a>
                <ul>
                    <li>
                        <a href="{% url 'loginApp:logout' %}">
                            <i class="glyphicon glyphicon-log-out">
                                <span>Logout</span>
                            </i>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <!-- 面包屑 -->
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item first"><a href="#" target="main_iframe">Overview</a></li>
            <li class="breadcrumb-item second"></li>
            <li class="breadcrumb-item active" aria-current="page"></li>
        </ol>
    </nav>
</header> <!-- .cd-main-header -->