DjMemoryGetSys/loginApp/urls.py
from django.urls import path
from .views import login, register, logout

app_name = 'loginApp'

urlpatterns = [
    path('', login, name='login'),
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),
]

DjMemoryGetSys/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('loginApp.urls'), name="loginApp1"),
    path('home/', include('homeApp.urls'), name='homeApp'),
    re_path(r'^.*$', include('homeApp.urls'), name="homeAll")
]

DjMemoryGetSys/loginApp/forms.py
# -*-coding:utf-8-*-
'''
    
'''

from django import  forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


class LoginForm(forms.Form):

    username = forms.CharField(
        label='用户名',
        min_length=3,
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "请输入用户名"}),
        error_messages={
            "required": "用户名不能为空",
            "min_length": "用户名最小长度为3位",
        },
    )
    password = forms.CharField(
        label="密码",
        min_length=6,
        error_messages={
            "min_length": "密码最小长度为6位",
            "required": "密码不能为空",
        },
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"}),
    )

    def clean(self):

        username = self.cleaned_data.get("username", "")
        password = self.cleaned_data.get("password", "")
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("用户名或密码错误")
        self.cleaned_data["user"] = user
        return self.cleaned_data


class RegisterForm(LoginForm):

    password_again = forms.CharField(
        label="确认密码",
        min_length=6,
        error_messages={
            "required": "确认密码不能为空",
            "min_length": "密码最小长度为6位",
        },
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "确认密码"}),
    )
    email = forms.EmailField(
        label="邮箱",
        required=False,
        error_messages={
            "required": "密码不能为空",
        },
        widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "请输入邮箱"})
    )

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("用户名已存在")
        return username

    def clean_email(self):
        email = self.cleaned_data["email"]
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError("邮箱已存在")

        return email

    def clean(self):
        password = self.cleaned_data.get("password", "")
        password_again = self.cleaned_data.get("password_again", "")

        if password != password_again:
            raise forms.ValidationError("两次密码不一致，请重新输入")

        return self.cleaned_data

DjMemoryGetSys/loginApp/views.py
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect
from django.contrib import auth
from .forms import RegisterForm, LoginForm, User


def register(request):
    if request.method == "GET":
        register_form = RegisterForm()
        return render(request, "register.html", context={"register_form": register_form})
    elif request.method == "POST":
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            username = register_form.cleaned_data["username"]
            password = register_form.cleaned_data["password"]
            email = register_form.cleaned_data.get("email", "")
            # 创建用户
            user = User.objects.create_user(username, email, password)
            auth.login(request, user)
            obj = redirect(reverse('homeApp:home'), {"username": user.username})
            obj.set_signed_cookie('user', user.username)
            return obj
        else:
            return render(request, "register.html", {"register_form": register_form})


def login(request):
    if request.method == "GET":
        username = request.GET.get("username")
        login_form = LoginForm()
        return render(request, "login.html", context={"login_form": login_form})
    elif request.method == "POST":
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            # 注意：验证用户名和密码是否正确放到forms中去验证了
            # login(request, request.user)  # 此处不能使用request.user,因为他还没有验证，是匿名用户
            # 所以需要在form中校验通过后传递过来user
            user = auth.authenticate(username=login_form.cleaned_data["user"], password=login_form.cleaned_data["password"])
            if user:
                # 使用auth.login方法加上sessioncookie
                auth.login(request, user)
                # 这段代码看不懂先往下面看
                # 如果校验通过则进去下一个页面,获取不到则默认跳转index的url
                if request.get_full_path() in ('/login/login', '/login/?next=/') or 'next=/home/index/' in request.get_full_path():
                    obj = redirect(reverse('homeApp:index'), (user))
                else:
                    obj = redirect(reverse('homeApp:home'), (user))
                # obj = render(request, "index.html", {"user": user})
                obj.set_signed_cookie('user', user)
                return obj
            else:
                return render(request, "login.html", {"login_form": login_form})
        else:
            return render(request, "login.html", {"login_form": login_form})


def logout(request):
    auth.logout(request)
    obj = redirect(reverse('loginApp:login'))
    obj.delete_cookie('user')
    return obj

DjMemoryGetSys/loginApp/templates/login.html
{% extends 'base.html' %}
{% block title %} 登录 {% endblock %}
{% block content %}
    <div>
        <div class="container" style="margin-top: 200px">
            <div class="row">
                <div class="col-lg-offset-4 col-mid-offset-4 col-xl-offset-4 col-lg-4 col-mid-4 col-xl-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">登录</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="post" novalidate>
                                {% csrf_token %}

        {#                        方法一： 写出form表单中的指定字段 #}
        {#                        {{ login_form.username.label_tag }}:#}
        {#                        {{ login_form.username }}#}
        {#                        <p class="text-danger">{{ login_form.errors.username.0 }}</p>#}
        {#                        {{ login_form.password.label_tag }}:#}
        {#                        {{ login_form.password }}#}
        {#                        <p class="text-danger">{{ login_form.errors.password.0 }}</p>#}
        {#                        <div class="text-danger">{{ login_form.non_field_errors }}</div>#}

        {#                        方法二： 遍历出form表单中的所有字段 #}
                                {% for field in login_form %}
                                    {{ field.label_tag }}
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
        {#                        此处错误信息会返回clean联合校验，也就是非单个字段校验的错误信息#}
                                <span class="text-danger pull-left">{{ login_form.non_field_errors }}</span><br />
                                <input type="submit" value="登录" class="btn btn-primary pull-left">
                                <a href="{% url 'loginApp:register' %}"><input type="button" value="注册" class="btn btn-primary pull-right"></a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}

{% endblock %}

DjMemoryGetSys/loginApp/templates/register.html
{% extends 'base.html' %}
{% block title %}
    注册
{% endblock %}

{% block content %}
    <div>
        <div class="container" style="margin-top: 200px">
            <div class="row">
                <div class="col-lg-offset-4 col-mid-offset-4 col-xl-offset-4 col-lg-4 col-mid-4 col-xl-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">注册</h3>
                        </div>
                        <div class="panel-body">
                            <form action="" method="post" novalidate>
                                {% csrf_token %}
                                {% for field in register_form %}
                                    {{ field.label_tag }}
                                    {{ field }}
                                    <p class="text-danger">{{ field.errors.as_text }}</p>
                                {% endfor %}
                                <span class="text-danger pull-left">{{ register_form.non_field_errors }}</span>
                                <br />
                                <input type="submit" value="注册" class="btn btn-primary pull-left">
                                <a href="{% url 'loginApp:login' %}">
                                    <input type="button" value="取消" class="btn btn-primary pull-right">
                                </a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}